---
title: "Anime: Un poco de historia"
# subtitle: "Una teoría antropológica y religiosa de la violencia humana"
author: "Diego Montes"
date: "2026-04-16"
categories: [2026, historia, anime]
---

## Resumen

Muchos seguramente hemos visto en nuestra infancia “dibujitos” como Dragon Ball, Pokemon, Los Caballeros del Zodiaco, etc, sin darnos cuenta de que pertenecian a un conjunto de animaciones de otro continente, de Japón, el llamado país del sol naciente. 
Entonces, ¿cómo fué que comenzó esta industria?: sus orígenes datan de la segunda década del sigo XX, con artistas como Ōten Shimokawa, los cuales no tenian una tarea facil, dado que los insumos importantes para la animación tenían altos costos, por ello debieron utilizar otras tecnicas para realizar su trabajo. Con el tiempo, grandes estudios de animación como Toey o Mushi, entraron en escena, causando el despegue definitivo de la industria en la televisión japonesa. De allí, con los años, llegaron a nuestro lado del mundo, marcando la infancia de muchos, y hasta hoy en dia, el genero es altamente consumido globalmente, con historias para todos los gustos.

## Datos

**Hora:** 14:00 hrs

**Lugar:** Sala de Física Teórica, FAMAF

*Seminario #17*

## El evento